args <- commandArgs(trailingOnly = TRUE)
script <- sub("^--file=", "", grep("^--file=", commandArgs(), value = TRUE)[1])
helper <- file.path(dirname(normalizePath(script)), "helpers.R")
if (!file.exists(helper)) stop("Summary helpers are not implemented yet")
source(helper, encoding = "UTF-8")
root <- if (length(args)) args[1] else tempfile("summary-demo-")
if (dir.exists(root)) stop("Demo destination exists; choose a new directory")
init_project(root)
raw <- data.frame(id = c("001", "002", "003", "004"), age = c("34", "unknown", "60", "60"), sex = c("1", "2", "1", NA))
age <- strict_numeric(raw$age, missing = c("", "unknown"))
sex <- labelled_factor(raw$sex, c("1" = "Male", "2" = "Female"))
stopifnot(identical(age, c(34, NA_real_, 60, 60)), identical(levels(sex), c("Male", "Female")))
stopifnot(identical(factor_codes(sex, c("1" = "Male", "2" = "Female")), raw$sex))
fails <- function(expr) inherits(tryCatch(force(expr), error = identity), "error")
stopifnot(fails(strict_numeric(c("34 years", "Inf"))))
stopifnot(fails(labelled_factor("9", c("1" = "Male", "2" = "Female"))))
tab <- categorical_summary(sex)
stopifnot(all(tab$n_valid == 3), all(tab$n_missing == 1), abs(sum(tab$percent) - 100) < 1e-8)
empty <- numeric_summary(rep(NA_real_, 3))
stopifnot(empty$n_valid == 0, is.na(empty$mean), is.na(empty$q1))
one <- numeric_summary(5)
stopifnot(is.na(one$sd), one$median == 5)
constant <- numeric_summary(rep(4, 3))
stopifnot(constant$sd == 0)
stopifnot(fails(numeric_summary(c(-1e308, 1e308))))
stopifnot(fails(categorical_summary(factor(c(NA, NA)))))
parse_error <- tryCatch(strict_numeric(c("12", "1e309")), error = conditionMessage)
stopifnot(grepl("2", parse_error), grepl("1e309", parse_error, fixed = TRUE))
clean <- data.frame(id = raw$id, age = age, sex = sex)
saveRDS(clean, file.path(root, "01_data/derived/data_clean.rds"))
encoded <- clean; encoded$sex <- factor_codes(sex, c("1" = "Male", "2" = "Female"))
write.csv(encoded, file.path(root, "01_data/derived/data_clean.csv"), row.names = FALSE, na = "")
write.csv(tab, file.path(root, "03_output/categorical_summary.csv"), row.names = FALSE)
write.csv(numeric_summary(age), file.path(root, "03_output/numeric_summary.csv"), row.names = FALSE)
writeLines("PASS: synthetic descriptive example; no regression or Word rendering tested here.", file.path(root, "03_output/validation.txt"))
cat("PASS clinical summary helper checks:", normalizePath(root), "\n")
