args <- commandArgs(trailingOnly = TRUE)
script <- sub("^--file=", "", grep("^--file=", commandArgs(), value = TRUE)[1])
helper <- file.path(dirname(normalizePath(script)), "helpers.R")
if (!file.exists(helper)) stop("Reconciliation helpers are not implemented yet")
source(helper, encoding = "UTF-8")
root <- if (length(args)) args[1] else tempfile("join-demo-")
if (dir.exists(root)) stop("Demo destination exists; choose a new directory")
init_project(root)
a <- data.frame(id = c("001", "002", "003"), town = c("Alpha", "Beta", NA))
b <- data.frame(name = c("Alpha", "Beta Office", NA), count = c(NA, 7, 99))
reports <- reconcile_keys(a, b, "town", "name", threshold = 7)
stopifnot(identical(reports$only_in_A$key, "Beta"), identical(reports$only_in_B$key, "Beta Office"))
stopifnot(nrow(reports$candidates) == 1L, reports$candidates$distance == 7)
exact <- safe_left_join(a, b, "town", "name")
stopifnot(identical(exact$id, a$id), identical(exact$match_status, c("matched", "unmatched", "missing_key")),
          is.na(exact$count[1]), is.na(exact$count[3]))
fails <- function(expr) inherits(tryCatch(force(expr), error = identity), "error")
stopifnot(fails(safe_left_join(a, rbind(b, b[1, ]), "town", "name")))
review <- data.frame(b_name = "Beta Office", a_name = "Beta", decision = "accept")
mapped <- apply_review(b, "name", review, a$town)
joined <- safe_left_join(a, mapped, "town", "name")
stopifnot(joined$count[2] == 7, nrow(joined) == 3L)
bad <- review; bad$a_name <- "Unknown"
stopifnot(fails(apply_review(b, "name", bad, a$town)))
stopifnot(fails(apply_review(b, "name", rbind(review, review), a$town)))
conflict <- review; conflict$decision <- "reject"
stopifnot(fails(apply_review(b, "name", rbind(review, conflict), a$town)))
stopifnot(fails(sum_preserve_na(c(1e308, 1e308))))
stopifnot(is.na(sum_preserve_na(c(NA_real_, NA_real_))), sum_preserve_na(c(2, NA)) == 2)
for (n in names(reports)) write.csv(reports[[n]], file.path(root, "01_data/derived", paste0(n, ".csv")), row.names = FALSE, na = "")
write.csv(joined, file.path(root, "01_data/derived/joined.csv"), row.names = FALSE, na = "")
writeLines("PASS: synthetic table workflow; review decisions in this demo are fixture data.", file.path(root, "03_output/validation.txt"))
cat("PASS reconciliation helper checks:", normalizePath(root), "\n")
